import Head from 'next/head'
import Script from 'next/script'
import { useEffect, useState } from 'react'
import styled from 'styled-components'

import GenkotsuDrawer from '@/components/GenkotsuDrawer'

const Main = styled.main`
  font-family: sans-serif;
  margin: 32px;
`

const Input = styled.input`
  max-width: 100%;
  font-size: 48px;
  font-family: var(--kei-font);
  margin-bottom: 24px;
  border-top: none;
  border-right: none;
  border-left: none;
  border-bottom: solid 1px #ccc;
`

const Footer = styled.footer`
  margin-top: 16px;
`

const Anchor = styled.a`
  color: #666;
  text-underline-offset: 4px;
`

const SnsParagraph = styled.div`
  display: flex;
  align-items: center;
  gap: 16px;
`

const Index = () => {
  const [text, setText] = useState('げんこつ')
  const [isClient, setIsClient] = useState(false)
  useEffect(() => {
    setIsClient(true)
  }, [])

  return (
    <>
      <Head>
        <title>げんこつ</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="website" property="og:type" />
        <meta content="げんこつ" property="og:title" />
        <meta content="みさえ〜〜" property="og:description" />
        <meta content="https://inaniwaudon.github.io/genkotsu/" property="og:url" />
        <meta content="げんこつ" property="og:site_name" />
        <meta content="https://inaniwaudon.github.io/genkotsu/genkotsu.png" property="og:image" />
        <meta content="summary_large_image" name="twitter:card" />
        <meta content="https://inaniwaudon.github.io/genkotsu/genkotsu.png" name="twitter:image" />
      </Head>
      <Main>
        <div>
          <Input type="text" value={text} onChange={(e) => setText(e.currentTarget.value)} />
        </div>
        <GenkotsuDrawer text={text} />
        <Footer>
          <p>
            表示用に「
            <Anchor href="http://font.sumomo.ne.jp/font_1.html">けいふぉんと</Anchor>
            」を使用しています。The keifont, that is included in this site, is distributed in{' '}
            <Anchor href="https://licenses.opensource.jp/Apache-2.0/Apache-2.0.html">the Apache License 2.0</Anchor>
          </p>
          <SnsParagraph>
            <Anchor href="https://github.com/inaniwaudon/genkotsu">GitHub</Anchor>
            {isClient && (
              <>
                <a
                  className="twitter-share-button"
                  data-show-count="false"
                  href="https://twitter.com/share?ref_src=twsrc%5Etfw"
                >
                  Tweet
                </a>
              </>
            )}
            <Script async={true} src="https://platform.twitter.com/widgets.js" />
          </SnsParagraph>
        </Footer>
      </Main>
    </>
  )
}

export default Index
