import Head from "next/head";
import styled from "styled-components";
import GenkotsuDrawer from "@/components/GenkotsuDrawer";
import { useState } from "react";

const Main = styled.main`
  margin: 32px;
`;

const Input = styled.input`
  font-size: 24px;
  margin-bottom: 8px;
  border-top: none;
  border-right: none;
  border-left: none;
  border-bottom: solid 1px #ccc;
`;

const Footer = styled.footer`
  margin-top: 16px;
`;

const Index = () => {
  const [text, setText] = useState("げんこつ");

  return (
    <>
      <Head>
        <title>げんこつ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Main>
        <div>
          <Input
            type="text"
            value={text}
            onChange={(e) => setText(e.currentTarget.value)}
          />
        </div>
        <GenkotsuDrawer text={text} />
        <Footer>
          表示用に「けいふぉんと」を使用しています。The keifont, that is
          included in this site, is distributed in the Apache License 2.0.
        </Footer>
      </Main>
    </>
  );
};

export default Index;
